### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by edward-hong** [vasansr/pro-mern-stack#4]
I've followed to the end of chapter 11. When I run the command "npm run dev-all" and then go to localhost:3000, there's no CSS. It's plain HTML. All the bootstrap classes are still there but bootstrap is not being linked for some reason.  Under the sources tab, I see the bootstrap.min.css file and when I click on it, it shows the template with the react elements instead of the bootstrap css file. Here's a link to my git repository https://github.com/edward-hong/pro-mern-stack. How can I get the CSS to look like the way it did before rendering on the server?

**Comment by vasansr** [comment]
The bootstrap files are supposed to come from the static directory. I don't see a static directory in your repo. Also, ensure that you soft-link (or copy, if you are using windows) the bootstrap directory from node_modules/bootstra/dist as described in Chapter 10, page 208, just before listing 10-1.

**Comment by edward-hong** [comment]
Sorry I think I've made a mistake with my ,gitignore file. I've included the folder named "dist" in the .gitignore file for the files I've compiled using npm but it's also excluded the folder I've copied from node_modules with "dist" as its name (I am using Windows). I've changed it to /dist instead of dist in .gitignore and now it's showing in the repository. Is the href path name /bootstrap/css/bootstrap.min.css correct for Windows as well? This was working before chapter 11

**Comment by edward-hong** [comment]
Also I've found this error message in the browser console:

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:3000/bootstrap/css/bootstrap.min.css".

I tried including type="text/css" in the link element in the template even though I know that this is no longer necessary in html. I thought I'd give it a try anyway but it didn't work

**Comment by vasansr** [comment]
I meant static. not dist.

**Comment by edward-hong** [comment]
In chapter 10 you mentioned that windows users should copy the entire dist directory into the static directory. So I had a subdirectory named dist inside of static copied from the bootstrap folder in node_modules https://github.com/edward-hong/pro-mern-stack/tree/master/static/dist. In the gitignore file I had listed the file to ignore any folder named dist to exclude my compiled code. But this excluded the dist file I copied as well. That is why originally you couldn't see the static folder in my git repo because it had been excluded. But this has been fixed.

**Comment by vasansr** [comment]
Your error is typical of the bootstrap.min.css file not being found under expected path. When any route is not resolved, we return a Page Not Found HTML and that is why you are seeing the HTML "template" instead of the CSS.

Your static directory should look like this:

```
static
  bootstrap
    css
      bootstrap.min.css
      bootstrap.css
      ...
    js
      ...
```
Try a few things in your browser
(a) http://localhost:3000/nonexistentfile.html
(b) http://localhost:3000/bootstrap/css/bootstrap.min.css
(c) Create a test.txt file under static, and then, http://localhost:3000/test.txt

You're sure to find the problem.

**Comment by vasansr** [comment]
I see the problem: the instructions missed out the fact that the dist directory has to be copied as bootstrap, not dist itself. If that fixes your issue, I'll label this issue as an errata item for windows.

**Comment by edward-hong** [comment]
Thank you! Everything is working as expected once I renamed the folder dist to bootstrap
